apiVersion: apps/v1
kind: Deployment
metadata: 
  name: django-api-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: django-api
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: django-api
        version: v1
    spec:
      containers:
        - name: classmart-backend
          image: andresmg42/classmart-backend
          ports:
            - containerPort: 8000
          env:
          - name: IS_PRODUCTION
            value: "True"

          envFrom:
            - secretRef:
                name: postgres-secret
            
          
