apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
      - name: django-migrations
        image: andresmg42/classmart-backend:latest
        command: ["python", "manage.py", "migrate"]
        env:
          - name: DJANGO_DEBUG
            value: "False"
        # Add database readiness check
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "pg_isready -h postgres-service -p 5432"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      restartPolicy: Never
  backoffLimit: 2